name = "catalyst_gql_api"
compatibility_date = "2023-12-01"
main = "./src/worker.ts"
node_compat = true

[dev]
ip = "localhost"
port = 5050
local_protocol = "http"

[[d1_databases]]
binding = "APP_DB" # available in your Worker on env.DB
database_name = "catalyst"
database_id = "87d35dfe-69b2-42cb-9aeb-45efacde0d14"
migrations_dir = "node_modules/@catalyst/schema/dist/flat_migrations" # Customize this value to rename the `migrations` folder