name = "catalyst_gql_api"
compatibility_date = "2023-12-01"
main = "./src/worker.ts"
node_compat = true

[dev]
ip = "localhost"
port = 5050
local_protocol = "http"

[[d1_databases]]
binding = "APP_DB" # available in your Worker on env.DB
database_name = "gql-catalyst-db"
database_id = "1be4d6a2-7e61-4346-a50e-f43fe8b8f938"
migrations_dir = "node_modules/@catalyst/schema/dist/migrations" # Customize this value to rename the `migrations` folder
