name = "authx-worker"
main = "src/index.ts"
compatibility_date = "2023-10-02"
node_compat = true

[env.jtaylor-dev]
name = "authx-worker-jtaylor-dev"

[env.jtaylor-dev.vars]
ZITADEL_ORG_AUTOMATION_CLIENT_ID ="authx-svc"
ZITADEL_TOKEN_VALIDATION_CLIENT_ID = "237555637289044059@remix-app"
ZITADEL_ENDPOINT = "https://devinstance-dxq2do.zitadel.cloud"
AUTHZED_ENDPOINT = "https://gateway-alpha.authzed.com/"