// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
import { OrganizationMatchmakingDO } from './src';

export interface Env {
	ORG_MATCHMAKING: DurableObjectNamespace<OrganizationMatchmakingDO>
}
