#:schema node_modules/wrangler/config-schema.json
name = "organization-matchmaking"
main = "src/index.ts"
compatibility_date = "2024-04-23"
compatibility_flags = ["nodejs_compat"]
account_id = "3be6f7bb0cc73869d555e1156586c1f2"

services = [
	{ binding = "USERCACHE", service = "user_credentials_cache"},
	{ binding = "AUTHZED", service = "authx_authzed_api"},
]

[[durable_objects.bindings]]
 name = "ORG_MATCHMAKING"
 class_name = "OrganizationMatchmakingDO"

[[migrations]]
tag = "v1"
new_classes = ["OrganizationMatchmakingDO"]

[[migrations]]
tag = "v2"




# STAGING VALUES
[env.staging]

durable_objects.bindings = [{name = "ORG_MATCHMAKING", class_name = "OrganizationMatchmakingDO"}]

services = [
	{ binding = "AUTHZED", service = "authx_authzed_api-staging"},
	{ binding = "USERCACHE", service = "user_credentials_cache-staging"}
]




# PRODUCTION VALUES
[env.production]

durable_objects.bindings = [{name = "ORG_MATCHMAKING", class_name = "OrganizationMatchmakingDO"}]

services = [
	{ binding = "AUTHZED", service = "authx_authzed_api-production"},
	{ binding = "USERCACHE", service = "user_credentials_cache-production"}
]
