#:schema node_modules/wrangler/config-schema.json
name = "organization-matchmaking"
main = "src/index.ts"
compatibility_date = "2024-04-23"
compatibility_flags = ["nodejs_compat"]

services = [
	{ binding = "USERCACHE", service = "user_credentials_cache"},
	{ binding = "AUTHZED", service = "authx_authzed_api"},
]

[[durable_objects.bindings]]
 name = "ORG_MATCHMAKING"
 class_name = "OrganizationMatchmakingDO"

[[migrations]]
tag = "v1"
new_classes = ["OrganizationMatchmakingDO"]

[[migrations]]
tag = "v2"


###################  STAGING VALUES ###################
[env.staging]

durable_objects.bindings = [{name = "ORG_MATCHMAKING", class_name = "OrganizationMatchmakingDO"}]

services = [
	{ binding = "AUTHZED", service = "authx_authzed_api-staging"},
	{ binding = "USERCACHE", service = "user_credentials_cache-staging"}
]




################### DEMO VALUES ###################
[env.demo]

durable_objects.bindings = [{name = "ORG_MATCHMAKING", class_name = "OrganizationMatchmakingDO"}]

services = [
	{ binding = "AUTHZED", service = "authx_authzed_api-demo"},
	{ binding = "USERCACHE", service = "user_credentials_cache-demo"}
]
