packages:
  - apps/*
  - packages/*
  - examples/*
catalog:
  "@chakra-ui/button": ^2.1.0
  "@chakra-ui/card": ^2.2.0
  "@chakra-ui/icons": ^2.1.1
  "@chakra-ui/layout": ^2.3.1
  "@chakra-ui/react": ^2.8.2
  "@chakra-ui/system": ^2.6.2
  "@chakra-ui/theme-tools": ^2.1.2
  "@cloudflare/next-on-pages": ^1.11.2
  "@cloudflare/workers-types": ^4.20250414.0
  "@cloudflare/vitest-pool-workers": ^0.8.22
  "@emotion/react": ^11.11.4
  "@eslint/js": ^9.24.0
  "@flydotio/dockerfile": ^0.5.7
  "@graphql-codegen/cli": ^5.0.2
  "@graphql-codegen/client-preset": ^4.2.5
  "@graphql-codegen/schema-ast": ^4.0.2
  "@graphql-codegen/typescript-graphql-request": ^6.2.0
  "@graphql-tools/stitch": ^9.1.0
  "@graphql-tools/utils": ^10.1.3
  "@graphql-tools/wrap": ^10.0.5
  "@heroicons/react": ^2.1.3
  "@monaco-editor/react": ^4.6.0
  "@oclif/core": ^3
  "@oclif/plugin-help": ^6
  "@oclif/plugin-plugins": ^4
  "@oclif/prettier-config": ^0.2.1
  "@oclif/test": ^3
  "@pothos/core": ^3.41.0
  "@trpc/server": ^10.45.2
  "@types/chai": ^4
  "@types/mocha": ^10
  "@types/uuid": ^9.0.8
  "@urql/core": ^4.3.0
  autoprefixer: ^10.4.19
  base64url: ^3.0.1
  chai: ^4
  dockerode: ^4.0.2
  eslint: ^9.24.0
  eslint-config-oclif: ^5
  eslint-config-oclif-typescript: ^3
  eslint-config-prettier: ^9.1.0
  express: ^4.19.2
  framer-motion: ^11.1.7
  geo-route-generator: ^1.3.0
  gqty: 3.0.0-alpha-7b21563c.0
  graphql: ^16.8.1
  graphql-request: ^6.1.0
  kysely: ^0.27.3
  kysely-d1: ^0.3.0
  listhen: ^1.7.2
  mocha: ^10
  oclif: ^4.4.2
  prettier: ^3.2.5
  react-markdown: ^9.0.1
  shodan-api: ^0.1.6
  shx: ^0.3.4
  socket.io: ^4.7.5
  socket.io-client: ^4.7.5
  swr: ^2.2.5
  ts-node: ^10.9.2
  tslog: ^4.9.2
  tsx: ^4.9.4
  turbo: ^1.13.0
  typescript: ^5.8.3
  unstorage: ^1.10.2
  uuid: ^9.0.1
  vitest: ~3.0.7
  wrangler: ^4.13.2
  xml-js: ^1.6.11
  kill-port: ^2.0.1
