name = "catalyst"
compatibility_date = "2024-04-15"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "./.vercel/output/static"

services = [
    { binding = "ISSUED_JWT_WORKER", service = "issued-jwt-registry" },
  { binding = "CATALYST_DATA_CHANNEL_REGISTRAR_API", service = "data_channel_registrar" },
  { binding = "AUTHX_TOKEN_API", service = "authx_token_api" },
  { binding = "AUTHX_AUTHZED_API", service = "authx_authzed_api"},
  { binding = "USER_CREDS_CACHE", service = "user-credentials-cache"},
  { binding = "ORGANIZATION_MATCHMAKING", service = "organization-matchmaking" }
]


## STAGING VALUES - per cloudflare documenation
#'Unlike Workers Environments, production and preview are the only two options available via [env.<ENVIRONMENT>].'
[env.preview] #leave this value as 'preview'
services = [
    { binding = "ISSUED_JWT_WORKER", service = "issued-jwt-registry-staging" },
    { binding = "CATALYST_DATA_CHANNEL_REGISTRAR_API", service = "data_channel_registrar-staging" },
    { binding = "AUTHX_TOKEN_API", service = "authx_token_api-staging" },
    { binding = "AUTHX_AUTHZED_API", service = "authx_authzed_api-staging" },
    { binding = "USER_CREDS_CACHE", service = "user-credentials-cache-staging" },
    { binding = "ORGANIZATION_MATCHMAKING", service = "organization-matchmaking-staging" }
]


# PRODUCTION VALUES
[env.production]
services = [
    { binding = "ISSUED_JWT_WORKER", service = "issued-jwt-registry-demo" },
    { binding = "CATALYST_DATA_CHANNEL_REGISTRAR_API", service = "data_channel_registrar-demo" },
    { binding = "AUTHX_TOKEN_API", service = "authx_token_api-demo" },
    { binding = "AUTHX_AUTHZED_API", service = "authx_authzed_api-demo" },
    { binding = "USER_CREDS_CACHE", service = "user-credentials-cache-demo" },
    { binding = "ORGANIZATION_MATCHMAKING", service = "organization-matchmaking-demo" }
]

