name = "catalyst"
compatibility_date = "2024-04-15"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "./.vercel/output/static"

services = [
    { binding = "ISSUED_JWT_WORKER", service = "issued_jwt_registry", entrypoint = "IssuedJWTRegistryWorker" },
  { binding = "CATALYST_DATA_CHANNEL_REGISTRAR_API", service = "data_channel_registrar" },
  { binding = "AUTHX_TOKEN_API", service = "authx_token_api" },
  { binding = "AUTHX_AUTHZED_API", service = "authx_authzed_api"},
  { binding = "USER_CREDS_CACHE", service = "user_credentials_cache"},
  { binding = "ORGANIZATION_MATCHMAKING", service = "organization-matchmaking" }
]


## STAGING VALUES
[env.preview]
services = [
    { binding = "ISSUED_JWT_WORKER", service = "issued-jwt-registry-staging", environment = "production" },
    { binding = "CATALYST_DATA_CHANNEL_REGISTRAR_API", service = "data_channel_registrar-staging", environment = "production" },
    { binding = "AUTHX_TOKEN_API", service = "authx_token_api-staging", environment = "production" },
    { binding = "AUTHX_AUTHZED_API", service = "authx_authzed_api-staging", environment = "production" },
    { binding = "USER_CREDS_CACHE", service = "user_credentials_cache-staging", environment = "production" },
    { binding = "ORGANIZATION_MATCHMAKING", service = "organization-matchmaking-staging", environment = "production" }
]


# PRODUCTION VALUES
#[env.production]
#services = [
#    { binding = "ISSUED_JWT_WORKER", service = "issued_jwt_registry-production", entrypoint = "IssuedJWTRegistryWorker" },
#    { binding = "CATALYST_DATA_CHANNEL_REGISTRAR_API", service = "data_channel_registrar-production", entrypoint = "RegistrarWorker" },
#    { binding = "AUTHX_TOKEN_API", service = "authx_token_api-production", entrypoint = "JWTWorker" },
#    { binding = "AUTHX_AUTHZED_API", service = "authx_authzed_api-production", entrypoint = "AuthzedWorker"},
#    { binding = "USER_CREDS_CACHE", service = "user_credentials_cache-production", entrypoint = "UserCredsCacheWorker"},
#    { binding = "ORGANIZATION_MATCHMAKING", service = "organization-matchmaking" }
#]