name = "catalyst-ui"
compatibility_date = "2024-04-15"
compatibility_flags = [ "nodejs_compat" ]

services = [
    { binding = "ISSUED_JWT_WORKER", service = "issued_jwt_registry", entrypoint = "IssuedJWTRegistryWorker" },
  { binding = "CATALYST_DATA_CHANNEL_REGISTRAR_API", service = "data_channel_registrar" },
  { binding = "AUTHX_TOKEN_API", service = "authx_token_api" },
  { binding = "AUTHX_AUTHZED_API", service = "authx_authzed_api"},
  { binding = "USER_CREDS_CACHE", service = "user_credentials_cache"}
]

