name = "catalyst-ui"
compatibility_date = "2024-04-05"
compatibility_flags = [ "nodejs_compat" ]

services = [
  { binding = "CATALYST_DATA_CHANNEL_REGISTRAR_API", service = "data_channel_registrar" },
  { binding = "AUTHX_TOKEN_API", service = "authx_token_api" },
  { binding = "AUTHX_AUTHZED_API", service = "authx_authzed_api"}
]

