name = "drizzle-graphql-d1"
main = "src/server.ts"
compatibility_date = "2024-05-18"

[[d1_databases]]
binding = "DB"
database_name = "jobs-db"
database_id = "" # 👈 Add your database_id here
preview_database_id = "jobs-db-preview"
