// Time duration constants for the application
export enum DEFAULT_STANDARD_DURATIONS {
    MS = 1,
    S = DEFAULT_STANDARD_DURATIONS.MS * 1000,
    M = DEFAULT_STANDARD_DURATIONS.S * 60,
    H = DEFAULT_STANDARD_DURATIONS.M * 60,
    D = DEFAULT_STANDARD_DURATIONS.H * 24,
    W = DEFAULT_STANDARD_DURATIONS.D * 7,
    MONTH = DEFAULT_STANDARD_DURATIONS.D * 30,
    Y = DEFAULT_STANDARD_DURATIONS.D * 365,
}
