name = "datachannel-adsb"
compatibility_date = "2024-04-15"
main = "index.ts"
account_id = "3be6f7bb0cc73869d555e1156586c1f2"
# We want to give this worker a public endpoint so we can easily add it as a datachannel.
workers_dev = true

[dev]
port = 4008

[vars]
#RAPID_API_KEY="RAPID_API_KEY can be set in .dev.vars for local development"

[env.staging.vars]
CATALYST_JWKS_URL = "https://gateway.catalyst.devintelops.io/.well-known/jwks.json"
#RAPID_API_KEY
[env.staging.route]
pattern = "datachannel-adsb.devintelops.io"
custom_domain = true

[env.demo.vars]
CATALYST_JWKS_URL = "https://gateway.catalyst.demointelops.io/.well-known/jwks.json"
#RAPID_API_KEY

[env.demo.route]
pattern = "datachannel-adsb.demointelops.io"
custom_domain = true


