name = "datachannel-adsb"
compatibility_date = "2024-04-15"
main = "index.ts"
account_id = "3be6f7bb0cc73869d555e1156586c1f2"
# We want to give this worker a public endpoint so we can easily add it as a datachannel.
workers_dev = true

[dev]
port = 4008