name = "data_channel_registrar"
compatibility_date = "2023-12-01"
main = "./src/index.ts"
node_compat = true

[vars]
D0_NAMESPACE = "development"

[[durable_objects.bindings]]
name = "REGISTRAR"
class_name = "Registrar"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Registrar"]

[dev]
ip = "localhost"
port = 5000
local_protocol = "http"
