name = "data_channel_registrar"
compatibility_date = "2024-04-05"
compatibility_flags = ["rpc"]
main = "./src/worker.ts"
node_compat = true
workers_dev = false

[dev]
ip = "localhost"
port = 5050


[durable_objects]
bindings = [{name = "DO", class_name = "Registrar"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Registrar"]
