name = "data_channel_registrar"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
main = "./src/worker.ts"
workers_dev = false

[dev]
ip = "localhost"
port = 5050


services = [
  { binding = "AUTHX_TOKEN_API", service = "authx_token_api" },
  { binding = "AUTHZED", service = "authx_authzed_api"},
  { binding = "USERCACHE", service = "user_credentials_cache"}
]


[durable_objects]
bindings = [{name = "DO", class_name = "Registrar"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Registrar"]




# STAGING VALUES
[env.staging]
services = [
  { binding = "AUTHX_TOKEN_API", service = "authx_token_api-staging" },
  { binding = "AUTHZED", service = "authx_authzed_api-staging" },
  { binding = "USERCACHE", service = "user_credentials_cache-staging" }
]
durable_objects.bindings = [{name = "DO", class_name = "Registrar"}]
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Registrar"]




# PRODUCTION VALUES
[env.production]
services = [
  { binding = "AUTHX_TOKEN_API", service = "authx_token_api-production" },
  { binding = "AUTHZED", service = "authx_authzed_api-production" },
  { binding = "USERCACHE", service = "user_credentials_cache-production" }
]
durable_objects.bindings = [{name = "DO", class_name = "Registrar"}]
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Registrar"]