// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
import { I_JWT_Registry_DO } from "./src";
interface Env {
	ISSUED_JWT_REGISTRY: DurableObjectNamespace<I_JWT_Registry_DO>;
	USERCACHE: Service<UserCredsCacheWorker>;
}
