// Generated by Wrangler by running `wrangler types` (hash: c1708c42b7f2cd0287a063fe645e9946)
// Runtime types generated with workerd@1.20250408.0 2024-04-19 nodejs_compat
declare namespace Cloudflare {
	interface Env {
		ISSUED_JWT_REGISTRY_DO: DurableObjectNamespace<import('./src/index').I_JWT_Registry_DO>;
		USERCACHE: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
