#:schema node_modules/wrangler/config-schema.json
name = "issued-jwt-registry"
main = "src/index.ts"
compatibility_date = "2024-04-19"
compatibility_flags = [ "nodejs_compat" ]
account_id = "3be6f7bb0cc73869d555e1156586c1f2"
services = [
    { binding = "USERCACHE", service = "user_credentials_cache" },
]
[dev]
ip = "localhost"
port = 5053

[[durable_objects.bindings]]
name = "ISSUED_JWT_REGISTRY_DO"
class_name = "I_JWT_Registry_DO"

[[migrations]]
tag = "v1"
new_classes = ["I_JWT_Registry_DO"]


[env.staging]
durable_objects.bindings = [{name = "ISSUED_JWT_REGISTRY_DO", class_name = "I_JWT_Registry_DO"}]
services = [
    { binding = "USERCACHE", service = "user_credentials_cache-staging" },
]
[env.demo]
durable_objects.bindings = [{name = "ISSUED_JWT_REGISTRY_DO", class_name = "I_JWT_Registry_DO"}]
services = [
    { binding = "USERCACHE", service = "user_credentials_cache-demo" },
]
