#:schema node_modules/wrangler/config-schema.json
name = "user-credentials-cache"
main = "src/index.ts"
compatibility_date = "2024-04-19"

# https://developers.cloudflare.com/durable-objects/
[durable_objects]
bindings = [{name = "CACHE", class_name = "UserCredsCache"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["UserCredsCache"]

[[migrations]]
tag = "v2"

############# STAGING VALUES #############
[env.staging]
durable_objects.bindings = [{name = "CACHE", class_name = "UserCredsCache"}]

############# DEMO VALUES #############
[env.demo]
durable_objects.bindings = [{name = "CACHE", class_name = "UserCredsCache"}]
