name = "data_channel_gateway"
compatibility_date = "2024-01-01"
compatibility_flags = [ "nodejs_compat" ]

services = [
    { binding = "DATA_CHANNEL_REGISTRAR", service = "data_channel_registrar"  },
    { binding = "AUTHX_TOKEN_API", service = "authx_token_api"}
]

[dev]
ip = "localhost"
port = 5051

# [vars]
# MY_VARIABLE = "production_value"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
