name = "data_channel_gateway"
compatibility_date = "2024-04-05"
compatibility_flags = [ "nodejs_compat" ]
main = "./src/index.ts"
account_id = "3be6f7bb0cc73869d555e1156586c1f2"

services = [
    { binding = "DATA_CHANNEL_REGISTRAR", service = "data_channel_registrar" },
    { binding = "AUTHX_TOKEN_API", service = "authx_token_api"},
    { binding = "AUTHX_AUTHZED_API", service = "authx_authzed_api" }
]

[dev]
ip = "localhost"
port = 5051



# STAGING VALUES
[env.staging]
services = [
    { binding = "DATA_CHANNEL_REGISTRAR", service = "data_channel_registrar-staging" },
    { binding = "AUTHX_TOKEN_API", service = "authx_token_api-staging"},
    { binding = "AUTHX_AUTHZED_API", service = "authx_authzed_api-staging" }
]

routes = [
    { pattern = "gateway.catalyst.devintelops.io", custom_domain = true }
]

# PRODUCTION VALUES
[env.production]
services = [
    { binding = "DATA_CHANNEL_REGISTRAR", service = "data_channel_registrar-production" },
    { binding = "AUTHX_TOKEN_API", service = "authx_token_api-production"},
    { binding = "AUTHX_AUTHZED_API", service = "authx_authzed_api-production" }
]
