[consumer]
catalyst_endpoint="http://localhost:4010/graphql"
catalyst_token="eyJhbGciOiJFZERTQSJ9.eyJpc3MiOiJjYXRhbHlzdDpzeXN0ZW06and0OmxhdGVzdCIsInN1YiI6Im9yYmlzb3BzL2cuc2FudGlhZ29Ab3JiaXNvcHMuY29tIiwiY2xhaW1zIjpbImI3NWU3ZDRmLWU3NjQtNDQwMy05MWY4LWRmZmMwN2FlYjllYyJdLCJhdWQiOiJjYXRhbHlzdDpzeXN0ZW06ZGF0YWNoYW5uZWxzIiwianRpIjoiNTU3ZGYxYzUtOTUwOC00NTM1LTllYzItY2Y5NTVkYjcxZGYwIiwibmJmIjoxNzQ3MTk2NDMzLCJpYXQiOjE3NDcxOTY0MzQsImV4cCI6MTc0NzgwMTIzNH0.jFAu3ybTO_dXcWHwkuD_eJ6eJX3twmbTSFOTjumPlElrxzV0UTJxDipZI4S6FWPpp_2zyNXD8A2wcFcuoIUcAg"
catalyst_query= """
{
    health
    errors
}
"""

catalyst_query_poll_interval_ms = 10000

[consumer.parser.aircraftWithinDistance.transform]
uid = "hex"
lat = "lat"
lon = "lon"
hae = "alt_geom"

[consumer.parser.aircraftWithinDistance.overwrite]
type = "a-f-A"
