name = "authx_token_api"
compatibility_date = "2024-04-05"
compatibility_flags = [ "nodejs_compat" ]
main = "src/index.ts"


services = [
	{ binding = "AUTHZED", service = "authx_authzed_api"},
	{ binding = "USERCACHE", service = "user-credentials-cache"}
]

[dev]
ip = "localhost"
port = 5052

# https://developers.cloudflare.com/durable-objects/
[durable_objects]
bindings = [{name = "KEY_PROVIDER", class_name = "JWTKeyProvider"}]


[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["JWTKeyProvider"]


############################ STAGING VALUES #################################
[env.staging]
services = [
	{ binding = "AUTHZED", service = "authx_authzed_api-staging"},
	{ binding = "USERCACHE", service = "user-credentials-cache-staging"}
]
durable_objects.bindings = [{name = "KEY_PROVIDER", class_name = "JWTKeyProvider"}]


# DEMO VALUES
[env.demo]
services = [
	{ binding = "AUTHZED", service = "authx_authzed_api-demo"},
	{ binding = "USERCACHE", service = "user-credentials-cache-demo"}
]
durable_objects.bindings = [{name = "KEY_PROVIDER", class_name = "JWTKeyProvider"}]
