name = "authx_token_api"
compatibility_date = "2024-04-05"
compatibility_flags = [ "nodejs_compat" ]
main = "src/index.ts"

[dev]
ip = "localhost"
port = 5052

# https://developers.cloudflare.com/durable-objects/
[durable_objects]
bindings = [{name = "HSM", class_name = "HSM"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["HSM"]
